version: '3.8'
services:
  php:
    image: ghcr.io/dennisduckaertap/my-application:latest
    environment:
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - dbdata:/var/lib/mysql   
volumes:
  dbdata:
